Update in ptc script

diff --git a/iso-profiles/netrunner/kdewaylandtest/desktop-overlay/usr/bin/prepare-testing-config b/iso-profiles/netrunner/kdewaylandtest/desktop-overlay/usr/bin/prepare-testing-config
--- a/iso-profiles/netrunner/kdewaylandtest/desktop-overlay/usr/bin/prepare-testing-config
+++ b/iso-profiles/netrunner/kdewaylandtest/desktop-overlay/usr/bin/prepare-testing-config
@@ -35,10 +35,10 @@ fi
 err_prepare_text="Could not make modifications in user's home manjaro tools configuration file\n"
 
 # use unstable repos
-sed -i "s|# target_branch=stable|target_branch=unstable|" $target_conf_file || { printf "$err_prepare_text";}
+sed -i "s|# target_branch=stable|target_branch=unstable|" $target_conf_file || { printf "$err_prepare_text"; }
 
 # change iso label from Manjaro into Netrunner
-sed -i 's|# dist_branding="MJRO"|dist_branding="NTRW"|' $target_conf_file || { printf "$err_prepare_text";}
+sed -i 's|# dist_branding="MJRO"|dist_branding="NTRW"|' $target_conf_file || { printf "$err_prepare_text"; }
 
 # change distribution release to BUILD_ID(with month without possible leading zero).day.hour format
 if [ -f $lsb_release_file ]; then
@@ -60,11 +60,13 @@ case "$(curl -s --max-time 5 -I https://github.com | sed 's/^[^ ]*  *\([0-9]\).*
   [23]) cd ${HOME}
         # sudo pacman-mirrors -f 5
         best_server_match=$(grep '^Server = ' /etc/pacman.d/mirrorlist | head -1 | cut -c10- | sed "s|/unstable/\$repo/\$arch||")
-        sed -i "s|# build_mirror=.*|build_mirror=${best_server_match}|" $target_conf_file || { printf "$err_prepare_text";}
+        sed -i "s|# build_mirror=.*|build_mirror=${best_server_match}|" $target_conf_file || { printf "$err_prepare_text"; }
+        echo "Substituted default build mirror"
         git clone https://github.com/notuxius/manjaro-tools-profile.git
-        echo "Profile isos can be built with 'buildiso -p kdewaylandtest' command"
+        echo "Downloaded profile is located in user's home directory"
+        echo "Profile ISOs can be built with 'buildiso -p kdewaylandtest' command"
         ;;
-  *) echo "Unable to select best mirror and download Netrunner Rolling Wayland/Xorg iso testing profile"
+  *) echo "Unable to select best mirror and download profile"
      echo "Please visit https://github.com/notuxius/manjaro-tools-profile for downloading"
      ;;
 esac
@@ -72,7 +74,7 @@ esac
 # select latest non-realtime kernel available
 latest_nonrt_kernel="$(mhwd-kernel -l | cut -c11- | grep '^[0-9]' | grep '[^rt]$' | sort -nr | head -n1)"
 
-sed -i "s|# kernel=.*|kernel=linux${latest_nonrt_kernel}|" $target_conf_file || { printf "$err_prepare_text";}
+sed -i "s|# kernel=.*|kernel=linux${latest_nonrt_kernel}|" $target_conf_file || { printf "$err_prepare_text"; }
 echo "Changing kernel in manjaro tools configuration file in your home directory to latest non-realtime available"
 
 echo 'Done.'
