Add selection of latest kernel into ptc script

diff --git a/iso-profiles/netrunner/kdewaylandtest/desktop-overlay/usr/bin/prepare-testing-config b/iso-profiles/netrunner/kdewaylandtest/desktop-overlay/usr/bin/prepare-testing-config
--- a/iso-profiles/netrunner/kdewaylandtest/desktop-overlay/usr/bin/prepare-testing-config
+++ b/iso-profiles/netrunner/kdewaylandtest/desktop-overlay/usr/bin/prepare-testing-config
@@ -25,11 +25,11 @@ fi
 if [ -f $(eval echo $target_conf_file) ]; then
     echo "You have existing manjaro tools configuration file in your home directory"
     cp -i $source_conf_file $target_conf_file
-    echo "Making changes in manjaro tools configuration file in your home directory"
+    echo "Replacing existing manjaro tools configuration file in your home directory"
 else
     echo "Copying system manjaro tools configuration file in your home directory"
     cp $source_conf_file $target_conf_file
-    echo "Making changes in manjaro tools configuration file in your home directory"
+    echo "Copying system manjaro tools configuration file into your home directory"
 fi
 
 err_prepare_text="Could not make modifications in user's home manjaro tools configuration file\n"
@@ -44,30 +44,36 @@ sed -i 's|# dist_branding="MJRO"|dist_branding="NTRW"|' $target_conf_file || { p
 if [ -f $lsb_release_file ]; then
     source /etc/lsb-release
     if [[ $DISTRIB_RELEASE =~ ^[0-9]{4}.[0-9]{1,2}$ ]]; then
-        sed -i 's|.*dist_release=.*|dist_release=\$(source /etc/lsb-release; echo "${DISTRIB_RELEASE}").\$(date +%-d.%-H)|' $target_conf_file || { printf "$err_prepare_text"; }
+        sed -i 's|# dist_release=.*|dist_release=\$(source /etc/lsb-release; echo "${DISTRIB_RELEASE}").\$(date +%-d.%-H)|' $target_conf_file || { printf "$err_prepare_text"; }
     elif [[ $DISTRIB_RELEASE =~ ^[0-9]{4}.[0-9]{1,2}.[0-9]{2}.[0-9]{2}$ ]]; then
-        sed -i 's|.*dist_release=.*|dist_release=$(source /etc/lsb-release; DISTRIB_RELEASE=${DISTRIB_RELEASE%.*}; echo "${DISTRIB_RELEASE%.*}").\$(date +%-d.%-H)|' $target_conf_file || { printf "$err_prepare_text"; }
+        sed -i 's|# dist_release=.*|dist_release=$(source /etc/lsb-release; DISTRIB_RELEASE=${DISTRIB_RELEASE%.*}; echo "${DISTRIB_RELEASE%.*}").\$(date +%-d.%-H)|' $target_conf_file || { printf "$err_prepare_text"; }
     else
         if [ -f $os_release_file ]; then
             source /usr/lib/os-release
-            sed -i 's|.*dist_release=.*|dist_release=$(source /usr/lib/os-release; DISTRIB_RELEASE=$(echo $BUILD_ID \| sed "s\|\\.0\|\\.\|"); echo "${DISTRIB_RELEASE}").\$(date +%-d.%-H)|' $target_conf_file || { printf "$err_prepare_text"; }
+            sed -i 's|# dist_release=.*|dist_release=$(source /usr/lib/os-release; DISTRIB_RELEASE=$(echo $BUILD_ID \| sed "s\|\\.0\|\\.\|"); echo "${DISTRIB_RELEASE}").\$(date +%-d.%-H)|' $target_conf_file || { printf "$err_prepare_text"; }
         fi
     fi
 fi
 
-# check if internet is availabe and clone latest github profile into user's home directory
+# check if internet is availabe - select best mirror and clone latest github profile into user's home directory
 case "$(curl -s --max-time 5 -I https://github.com | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
   [23]) cd ${HOME}
         # sudo pacman-mirrors -f 5
-        best_server_match=$(grep '^Server = ' /etc/pacman.d/mirrorlist | head -1 | cut -c10- | sed "s|unstable/\$repo/\$arch||")
-        sed -i "s|# build_mirror=.*|build_mirror=${best_server_match}|" $target_conf_file
+        best_server_match=$(grep '^Server = ' /etc/pacman.d/mirrorlist | head -1 | cut -c10- | sed "s|/unstable/\$repo/\$arch||")
+        sed -i "s|# build_mirror=.*|build_mirror=${best_server_match}|" $target_conf_file || { printf "$err_prepare_text";}
         git clone https://github.com/notuxius/manjaro-tools-profile.git
-        echo "Wayland/Xorg isos can be built with 'buildiso -p kdewaylandtest' command"
+        echo "Profile isos can be built with 'buildiso -p kdewaylandtest' command"
         ;;
-  *) echo "Unable to download Netrunner Rolling Wayland/Xorg iso testing profile"
+  *) echo "Unable to select best mirror and download Netrunner Rolling Wayland/Xorg iso testing profile"
      echo "Please visit https://github.com/notuxius/manjaro-tools-profile for downloading"
      ;;
 esac
+
+# select latest non-realtime kernel available
+latest_nonrt_kernel="$(mhwd-kernel -l | cut -c11- | grep '^[0-9]' | grep '[^rt]$' | sort -nr | head -n1)"
+
+sed -i "s|# kernel=.*|kernel=linux${latest_nonrt_kernel}|" $target_conf_file || { printf "$err_prepare_text";}
+echo "Changing kernel in manjaro tools configuration file in your home directory to latest non-realtime available"
 
 echo 'Done.'
 exit 0
