Check options before further execution of ptc script, closes #1
Former-commit-id: 8be361db59d230b5005c5145d558dd852af01167 [formerly a508c7ee37a9f9c936fc71d797af04d46de8634f]
Former-commit-id: 384ce707476130499ccd84b9e5118c421fd2427d

diff --git a/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config b/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config
--- a/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config
+++ b/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config
@@ -1,10 +1,30 @@
 #!/bin/bash
 
+# set -x
+
 echo
 
 if [[ $EUID -eq 0 ]]; then
     echo "This script must not be run as root. Exiting..."
     exit 1
+fi
+
+err_opt_text="Use -m/-c or -f/-u single option for desktop packages toggling. Exiting..."
+
+if [[ ${#1} -gt 2 ]]; then
+    echo "$err_opt_text"
+    exit 1
+fi
+
+opts='mcfu'
+
+if [[ ${#1} -gt 1 ]]; then
+    getopts "${opts}" arg
+
+    if [[ $arg == "?" ]]; then
+        echo "$err_opt_text"
+        exit 1
+    fi
 fi
 
 # check free space in and display warning 
@@ -13,13 +33,6 @@ disk_free_space=$(df -h / | tail -1 | awk '{print $4}' | sed s/G//)
 if [[ $(printf '%.*f' 0 $disk_free_space) -lt 30 ]]; then
     echo "Low free disk space on root partition - profile might not built"
     echo
-fi
-
-err_opt_text="Use -m/-c or -f/-u single option for desktop packages toggling. Exiting..."
-
-if [[ ${#1} -gt 2 ]]; then
-    echo "$err_opt_text"
-    exit 1
 fi
 
 cd ${HOME}
@@ -51,9 +64,6 @@ mhwd_packages_file=$(eval echo plasma-wayland-testing-manjaro-tools-profile/iso-
 
 # err_prepare_text="Cannot modify one of the defaults in current user's home manjaro tools configuration file\n"
 err_prepare_text="was not modified in current user's home manjaro tools configuration file\n"
-err_profile_text="Cannot make modifications in manjaro tools profile configuration file\n"
-err_desktop_packages_min_text="Desktop packages file is already set for minimal build - no modifications were made in it"
-err_desktop_packages_full_text="Desktop packages file is already set for full build - no modifications were made in it"
 
 # check if current current user's home config file already exists - and displays info and confirmation for overwriting it -
 # then copy system-wide manjaro tools config file into current current user's home directory for further modifications - 
@@ -257,58 +267,64 @@ case "$(curl -s --max-time 10 -I https://github.com | sed 's/^[^ ]*  *\([0-9]\).
         ;;
 esac
 
-if [[ ${#1} -gt 1 ]]; then
-    if [[ -w $desktop_packages_file ]]; then
-        opts='mcfu'
+err_profile_text="Cannot make modifications in manjaro tools profile configuration file\n"
+err_desktop_packages_min_text="Desktop packages file is already set for minimal build - no modifications were made in it"
+err_desktop_packages_full_text="Desktop packages file is already set for full build - no modifications were made in it"
+info_rerun_text="Rerun this script after manual change of kernel version - for packaging available kernel modules and drivers"
+info_profile_command_text="Profile ISOs can be built with 'buildiso -p plasmawaylandtest' command"
 
-        while getopts "${opts}" arg; do
-            case "${arg}" in
-                m|c) # comment/remove additional desktop packages and systemd services
-                    # change distribution release to ...codename-minimal-year.month.day.hour... version format
-                    echo "Minimal build - without some additional desktop packages and systemd services"
-
-                    cat $desktop_packages_file | grep -q '^[^# ].*# minimal-packages-toggle$' && sed -i 's|^\([^# ].*\)# minimal-packages-toggle$|# \1# minimal-packages-toggle|g' $desktop_packages_file || echo "$err_desktop_packages_min_text"
-                    sed -i "s|.*dist_release=.*|dist_release=\$(source ${lsb_release_file}; echo \${DISTRIB_CODENAME,,})-minimal-\$(date --utc +%Y.%-m.%-d.%-H)|" $target_conf_file || printf "$err_prepare_text"
-                    sed -i "/^# minimal-services-toggle/! s| 'org.cups.cupsd'||" $profile_conf_file || printf "$err_profile_text" 
-                    sed -i "/^# minimal-services-toggle/! s| 'smbd'||" $profile_conf_file || printf "$err_profile_text" 
-                    sed -i "/^# minimal-services-toggle/! s| 'nmbd'||" $profile_conf_file || printf "$err_profile_text"
-                    echo
-                    ;;
-                
-                f|u) # uncomment/include additional desktop packages and systemd services
-                    # change distribution release to ...codename-year.month.day.hour... version format
-                    echo "Full build - with some additional desktop packages and systemd services"
-
-                    cat $desktop_packages_file | grep -q '^# .*# minimal-packages-toggle$' && sed -i 's|^# \(.*\)# minimal-packages-toggle$|\1# minimal-packages-toggle|g' $desktop_packages_file || echo "$err_desktop_packages_full_text"
-                    sed -i "s|.*dist_release=.*|dist_release=\$(source ${lsb_release_file}; echo \${DISTRIB_CODENAME,,})-\$(date --utc +%Y.%-m.%-d.%-H)|" $target_conf_file || printf "$err_prepare_text"
-                    sed -i "/org.cups.cupsd/! s|\(^enable_systemd=.*[^)]\)|\1 'org.cups.cupsd'|" $profile_conf_file || printf "$err_profile_text"
-                    sed -i "/smbd/! s|\(^enable_systemd=.*[^)]\)|\1 'smbd'|" $profile_conf_file || printf "$err_profile_text"
-                    sed -i "/nmbd/! s|\(^enable_systemd=.*[^)]\)|\1 'nmbd'|" $profile_conf_file || printf "$err_profile_text"
-                    echo
-                    ;;
-                
-                 *) echo "$err_opt_text"
-                    exit 1
-                    ;;
-            esac
-        done
+# using arguments fetched with 'getopts' command at the begging of the script
+if [[ -w $desktop_packages_file ]]; then
+    case "${arg}" in
+        m|c) # comment/remove additional desktop packages and systemd services
+            # change distribution release to ...codename-minimal-year.month.day.hour... version format
+            echo "Minimal build - without some additional desktop packages and systemd services"
+            
+            cat $desktop_packages_file | grep -q '^[^# ].*# minimal-packages-toggle$' && sed -i 's|^\([^# ].*\)# minimal-packages-toggle$|# \1# minimal-packages-toggle|g' $desktop_packages_file || echo "$err_desktop_packages_min_text"
+            sed -i "s|.*dist_release=.*|dist_release=\$(source ${lsb_release_file}; echo \${DISTRIB_CODENAME,,})-minimal-\$(date --utc +%Y.%-m.%-d.%-H)|" $target_conf_file || printf "$err_prepare_text"
+            sed -i "/^# minimal-services-toggle/! s| 'org.cups.cupsd'||" $profile_conf_file || printf "$err_profile_text" 
+            sed -i "/^# minimal-services-toggle/! s| 'smbd'||" $profile_conf_file || printf "$err_profile_text" 
+            sed -i "/^# minimal-services-toggle/! s| 'nmbd'||" $profile_conf_file || printf "$err_profile_text"
+            echo
+            echo "$info_rerun_text"
+            echo
+            echo "$info_profile_command_text"
+            echo
+            ;;
         
-        # echo "Contents of desktop packages file after toggling comments:"
-        # cat $desktop_packages_file
-        
-    else
-        echo "Cannot make modifications in desktop packages file"
+        f|u) # uncomment/include additional desktop packages and systemd services
+            # change distribution release to ...codename-year.month.day.hour... version format
+            echo "Full build - with some additional desktop packages and systemd services"
+    
+            cat $desktop_packages_file | grep -q '^# .*# minimal-packages-toggle$' && sed -i 's|^# \(.*\)# minimal-packages-toggle$|\1# minimal-packages-toggle|g' $desktop_packages_file || echo "$err_desktop_packages_full_text"
+            sed -i "s|.*dist_release=.*|dist_release=\$(source ${lsb_release_file}; echo \${DISTRIB_CODENAME,,})-\$(date --utc +%Y.%-m.%-d.%-H)|" $target_conf_file || printf "$err_prepare_text"
+            sed -i "/org.cups.cupsd/! s|\(^enable_systemd=.*[^)]\)|\1 'org.cups.cupsd'|" $profile_conf_file || printf "$err_profile_text"
+            sed -i "/smbd/! s|\(^enable_systemd=.*[^)]\)|\1 'smbd'|" $profile_conf_file || printf "$err_profile_text"
+            sed -i "/nmbd/! s|\(^enable_systemd=.*[^)]\)|\1 'nmbd'|" $profile_conf_file || printf "$err_profile_text"
+            echo
+            echo "$info_rerun_text"
+            echo
+            echo "$info_profile_command_text"
+            echo
+            ;;
+    esac
+    
+    if [[ -z ${@} ]]; then
+        echo "Current build - desktop packages and systemd services were not modified"
+        echo
+        echo "$info_rerun_text"
+        echo
+        echo "$info_profile_command_text"
         echo
     fi
+
+    # echo "Contents of desktop packages file after toggling comments:"
+    # cat $desktop_packages_file
     
 else
-    echo "Current build - desktop packages and systemd services were not modified"
+    echo "Cannot make modifications in desktop packages file"
     echo
 fi
 
-echo "Rerun this script after manual change of kernel version - for packaging available kernel modules and drivers"
-echo
-echo "Profile ISOs can be built with 'buildiso -p plasmawaylandtest' command"
-echo
 echo 'Done.'
 exit 0
