Updates in ptc, fix small bugs

diff --git a/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config b/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config
--- a/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config
+++ b/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config
@@ -55,8 +55,6 @@ if [[ ! (( "${@}" == "-m" || "${@}" == "-f" || "${@}" == "" )) ]]; then
     exit 1
 fi
 
-# opts='mfd'
-
 # correct_profile=false
 
 # while getopt "${opts}" arg; do
@@ -195,127 +193,117 @@ echo
 #     fi
 # fi
 
-if [[ "$internet_avail" = true ]]; then
-    git_clone_profile='git clone https://github.com/notuxius/plasma-wayland-testing-manjaro-tools-profile.git' # 2> /dev/null)'
-    
-    read -p "Update mirrors list for selecting best build mirror and profile kernel? " -n 1 -r
-    if [[ $REPLY =~ ^[Yy]$ ]]; then
-        echo
-        echo
-        sudo pacman-mirrors -f 5
-        echo
-        sudo pacman -Syy
-        echo
-        sudo pacman -Fyy
-        echo
-    else
-        echo
-        echo
-    fi
+git_clone_profile='git clone https://github.com/notuxius/plasma-wayland-testing-manjaro-tools-profile.git' # 2> /dev/null)'
 
-    # select best build mirror
-    best_server_match=$(grep '^Server = ' /etc/pacman.d/mirrorlist | head -1 | cut -c10- | sed "s|/\(un\)*stable/.*||")
+read -p "Update mirrors list for selecting best build mirror and profile kernel? " -n 1 -r
+if [[ $REPLY =~ ^[Yy]$ ]]; then
+    echo
+    echo
+    sudo pacman-mirrors -f 5
+    echo
+    sudo pacman -Syy
+    echo
+    sudo pacman -Fyy
+    echo
+else
+    echo
+    echo
+fi
+
+# select best build mirror
+best_server_match=$(grep '^Server = ' /etc/pacman.d/mirrorlist | head -1 | cut -c10- | sed "s|/\(un\)*stable/.*||")
+
+if [[ -r $target_conf_file && -w $target_conf_file ]]; then
+    cat $target_conf_file | grep -q '# build_mirror=' && sed -i "s|# build_mirror=.*|build_mirror=${best_server_match}|" $target_conf_file || printf "Profile build mirror $err_prepare_text"
     
-    if [[ -r $target_conf_file && -w $target_conf_file ]]; then
-        cat $target_conf_file | grep -q '# build_mirror=' && sed -i "s|# build_mirror=.*|build_mirror=${best_server_match}|" $target_conf_file || printf "Profile build mirror $err_prepare_text"
-        
-        current_build_mirror=$(cat $target_conf_file | grep -E '^build_mirror=' | sed "s|build_mirror=||")
-        
-        echo "Current profile build mirror - ${current_build_mirror}"
-        echo
-        
-        # select latest non-realtime kernel available in unstable repo
-        latest_nonrt_kernel=$(wget -q -O - $best_server_match/unstable/core/x86_64/core.db.tar.gz | tar -tz | grep '^linux[4-9]' | grep -v 'headers' | grep -v 'desc' | sed "s|-.*||" | sort -Vr | head -n1)
-        cat $target_conf_file | grep -q '# kernel=' && sed -i "s|# kernel=.*|kernel=${latest_nonrt_kernel}|" $target_conf_file || printf "Profile kernel $err_prepare_text"
-        
-        if cat $target_conf_file | grep -q '^# kernel'; then
-            current_kernel=$(sed -n "/^# kernel/ s|# kernel=||p" $target_conf_file)
-        else
-            current_kernel=$(sed -n "/^kernel/ s|kernel=||p" $target_conf_file)
-        fi
-    fi
+    current_build_mirror=$(cat $target_conf_file | grep -E '^build_mirror=' | sed "s|build_mirror=||")
     
-    echo "Current profile kernel - ${current_kernel}"
+    echo "Current profile build mirror - ${current_build_mirror}"
     echo
     
+    # select latest non-realtime kernel available in unstable repo
+    latest_nonrt_kernel=$(wget -q -O - $best_server_match/unstable/core/x86_64/core.db.tar.gz | tar -tz | grep '^linux[4-9]' | grep -v 'headers' | grep -v 'desc' | sed "s|-.*||" | sort -Vr | head -n1)
+    cat $target_conf_file | grep -q '# kernel=' && sed -i "s|# kernel=.*|kernel=${latest_nonrt_kernel}|" $target_conf_file || printf "Profile kernel $err_prepare_text"
+    
+    if cat $target_conf_file | grep -q '^# kernel'; then
+        current_kernel=$(sed -n "/^# kernel/ s|# kernel=||p" $target_conf_file)
+    else
+        current_kernel=$(sed -n "/^kernel/ s|kernel=||p" $target_conf_file)
+    fi
+fi
+
+echo "Current profile kernel - ${current_kernel}"
+echo
+
 #         if [[ -x $(which mhwd-kernel 2> /dev/null) ]]; then
 #             printf "Other v4.x kernels:\n"
 #             mhwd-kernel -l | cut -c6- | grep '^linux[4-9]' | grep -vw "${latest_nonrt_kernel}" | sort -Vr
 #         fi
 
 
-    # echo "Downloading build profile folder into current user's home folder..."
-    if [[ ! -d plasma-wayland-testing-manjaro-tools-profile/ ]]; then
-        eval $git_clone_profile
-        
-        if [[ $? -eq 0 ]]; then
-            default_profile_download=true
-        fi
-        echo
+# echo "Downloading build profile folder into current user's home folder..."
+if [[ ! -d plasma-wayland-testing-manjaro-tools-profile/ ]]; then
+    eval $git_clone_profile
+    
+    if [[ $? -eq 0 ]]; then
+        default_profile_download=true
     fi
+    echo
+fi
 
-    echo "Looking for available kernel modules and drivers..."
+echo "Looking for available kernel modules and drivers..."
+echo
+
+available_kernel_modules=$(wget -q -O - ${best_server_match}/unstable/extra/x86_64/extra.db.tar.gz | tar -tz | grep -v 'desc' | grep ${current_kernel} | sed -r "s|-[0-9]+\.[0-9].*||" | sed -r "s|-[0-9]+\:[0-9].*||" | sed -r "s|-[0-9]{4}.*||" | sed "s|${current_kernel}|KERNEL|")
+
+if [[ -w $desktop_packages_file && -w $live_packages_file && -w $mhwd_packages_file ]]; then
+    # comment all modules and drivers
+    sed -i "/^[^#].*# available-kernel-modules-toggle$/ s|\(.*\)|# \1|" $desktop_packages_file
+    sed -i "/^[^#].*# available-kernel-drivers-toggle$/ s|\(.*\)|# \1|" $desktop_packages_file
+    
+    sed -i "/^[^#].*# available-kernel-modules-toggle$/ s|\(.*\)|# \1|" $live_packages_file
+    sed -i "/^[^#].*# available-kernel-drivers-toggle$/ s|\(.*\)|# \1|" $live_packages_file
+    
+    sed -i "/^[^#].*# available-kernel-modules-toggle$/ s|\(.*\)|# \1|" $mhwd_packages_file
+    sed -i "/^[^#].*# available-kernel-drivers-toggle$/ s|\(.*\)|# \1|" $mhwd_packages_file
+    
+    # uncomment only available modules
+    while read -r line; do
+        sed -i "/${line} .*# available-kernel-modules-toggle$/ s|^# \(.*\)${line}|\1${line}|" $desktop_packages_file
+    done <<< $available_kernel_modules
+    
+    while read -r line; do
+        sed -i "/${line} .*# available-kernel-modules-toggle$/ s|^# \(.*\)${line}|\1${line}|" $live_packages_file
+    done <<< $available_kernel_modules
+    
+    while read -r line; do
+        sed -i "/${line} .*# available-kernel-modules-toggle$/ s|^# \(.*\)${line}|\1${line}|" $mhwd_packages_file
+    done <<< $available_kernel_modules
+
+    available_kernel_drivers=$(sed "s|KERNEL-||" <<< $available_kernel_modules)
+    
+    # uncomment only available drivers
+    while read -r line; do
+        sed -i "/$line-utils .*# available-kernel-drivers-toggle$/ s|^# ||" $mhwd_packages_file
+    done <<< $available_kernel_drivers
+
+    selected_kernel_modules=$(grep '^[^#].* # available-kernel-modules-toggle$' $desktop_packages_file | sed "s|^>nonfree_default ||" | sed "s|^>nonfree_multilib ||" | sed "s|KERNEL-||"| sed "s|# available-kernel-modules-toggle$||"; grep '^[^#].* # available-kernel-modules-toggle$' $live_packages_file | sed "s|^>nonfree_default ||" | sed "s|^>nonfree_multilib ||" | sed "s|KERNEL-||"| sed "s|# available-kernel-modules-toggle$||"; grep '^[^#].* # available-kernel-modules-toggle$' $mhwd_packages_file | sed "s|^>nonfree_default ||" | sed "s|^>nonfree_multilib ||" | sed "s|KERNEL-||"| sed "s|# available-kernel-modules-toggle$||")
+    
+    selected_kernel_modules=$(sort <<< $selected_kernel_modules | uniq)
+    
+    printf "Selected kernel modules:\n${selected_kernel_modules}"
+    echo
     echo
     
-    available_kernel_modules=$(wget -q -O - ${best_server_match}/unstable/extra/x86_64/extra.db.tar.gz | tar -tz | grep -v 'desc' | grep ${current_kernel} | sed -r "s|-[0-9]+\.[0-9].*||" | sed -r "s|-[0-9]+\:[0-9].*||" | sed -r "s|-[0-9]{4}.*||" | sed "s|${current_kernel}|KERNEL|")
+    selected_kernel_drivers=$(grep '^[^#].* # available-kernel-drivers-toggle$' $mhwd_packages_file | sed "s|^>nonfree_default ||" | sed "s|^>nonfree_multilib ||" | sed "s|# available-kernel-drivers-toggle$||")
     
-    if [[ -w $desktop_packages_file && -w $live_packages_file && -w $mhwd_packages_file ]]; then
-        # comment all modules and drivers
-        sed -i "/^[^#].*# available-kernel-modules-toggle$/ s|\(.*\)|# \1|" $desktop_packages_file
-        sed -i "/^[^#].*# available-kernel-drivers-toggle$/ s|\(.*\)|# \1|" $desktop_packages_file
-        
-        sed -i "/^[^#].*# available-kernel-modules-toggle$/ s|\(.*\)|# \1|" $live_packages_file
-        sed -i "/^[^#].*# available-kernel-drivers-toggle$/ s|\(.*\)|# \1|" $live_packages_file
-        
-        sed -i "/^[^#].*# available-kernel-modules-toggle$/ s|\(.*\)|# \1|" $mhwd_packages_file
-        sed -i "/^[^#].*# available-kernel-drivers-toggle$/ s|\(.*\)|# \1|" $mhwd_packages_file
-        
-        # uncomment only available modules
-        while read -r line; do
-            sed -i "/${line} .*# available-kernel-modules-toggle$/ s|^# \(.*\)${line}|\1${line}|" $desktop_packages_file
-        done <<< $available_kernel_modules
-        
-        while read -r line; do
-            sed -i "/${line} .*# available-kernel-modules-toggle$/ s|^# \(.*\)${line}|\1${line}|" $live_packages_file
-        done <<< $available_kernel_modules
-        
-        while read -r line; do
-            sed -i "/${line} .*# available-kernel-modules-toggle$/ s|^# \(.*\)${line}|\1${line}|" $mhwd_packages_file
-        done <<< $available_kernel_modules
-
-        available_kernel_drivers=$(sed "s|KERNEL-||" <<< $available_kernel_modules)
-        
-        # uncomment only available drivers
-        while read -r line; do
-            sed -i "/$line-utils .*# available-kernel-drivers-toggle$/ s|^# ||" $mhwd_packages_file
-        done <<< $available_kernel_drivers
+    selected_kernel_drivers=$(sort <<< $selected_kernel_drivers | uniq)
     
-        selected_kernel_modules=$(grep '^[^#].* # available-kernel-modules-toggle$' $desktop_packages_file | sed "s|^>nonfree_default ||" | sed "s|^>nonfree_multilib ||" | sed "s|KERNEL-||"| sed "s|# available-kernel-modules-toggle$||"; grep '^[^#].* # available-kernel-modules-toggle$' $live_packages_file | sed "s|^>nonfree_default ||" | sed "s|^>nonfree_multilib ||" | sed "s|KERNEL-||"| sed "s|# available-kernel-modules-toggle$||"; grep '^[^#].* # available-kernel-modules-toggle$' $mhwd_packages_file | sed "s|^>nonfree_default ||" | sed "s|^>nonfree_multilib ||" | sed "s|KERNEL-||"| sed "s|# available-kernel-modules-toggle$||")
-        
-        selected_kernel_modules=$(sort <<< $selected_kernel_modules | uniq)
-        
-        printf "Selected kernel modules:\n${selected_kernel_modules}"
-        echo
-        echo
-        
-        selected_kernel_drivers=$(grep '^[^#].* # available-kernel-drivers-toggle$' $mhwd_packages_file | sed "s|^>nonfree_default ||" | sed "s|^>nonfree_multilib ||" | sed "s|# available-kernel-drivers-toggle$||")
-        
-        selected_kernel_drivers=$(sort <<< $selected_kernel_drivers | uniq)
-        
-        printf "Selected kernel drivers:\n${selected_kernel_drivers}"
-        echo
-        echo
-    else
-        echo "Unable to select available kernel modules and drivers"
-        echo
-    fi
-    
+    printf "Selected kernel drivers:\n${selected_kernel_drivers}"
+    echo
+    echo
 else
-    echo "Unable to select best build mirror and latest profile kernel"
-    echo "They can be changed manually in manjaro tools configuration file in current user's home folder"
-    echo
-    echo "Unable to download build profile"
-    echo "It can be obtained at https://github.com/notuxius/plasma-wayland-testing-manjaro-tools-profile"
+    echo "Unable to select available kernel modules and drivers"
     echo
 fi
 
@@ -335,6 +323,8 @@ if [[ -z ${@} ]]; then
 #         echo "$info_profile_command_text"
 #         echo
 fi
+
+opts='mfd'
 
 while getopts "${opts}" arg; do
 
