Select latest kernel from any branch and updates in ptc script
Former-commit-id: b4b5340db26248bd1b4f59cdc5b2d7b1443609f3 [formerly ba20e3655e298ff80c728f09dc53c0c4ab835a92]
Former-commit-id: fa46b8de077f95bfef248c4ba15ca4f80d61809c

diff --git a/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config b/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config
--- a/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config
+++ b/iso-profiles/netrunner/plasmawaylandtest/desktop-overlay/usr/bin/prepare-testing-config
@@ -41,7 +41,7 @@ sed -i "s|# target_branch=stable|target_branch=unstable|" $target_conf_file || {
 sed -i 's|# dist_branding="MJRO"|dist_branding="NTRW"|' $target_conf_file || { printf "$err_prepare_text"; }
 
 # change distribution release to ...codename-month.day.hour... version format
-if [[ -w $lsb_release_file ]]; then
+if [[ -r $lsb_release_file ]]; then
 sed -i "s|# dist_release=.*|dist_release=\$(source ${lsb_release_file}; echo \${DISTRIB_CODENAME,,})-\$(date --utc +%Y.%-m.%-d.%-H)|" $target_conf_file || { printf "$err_prepare_text"; }
 fi
 
@@ -63,22 +63,25 @@ fi
 # check if internet is availabe - select best mirror and clone latest github profile into user's home directory
 case "$(curl -s --max-time 10 -I https://github.com | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
   [23]) echo "'sudo pacman-mirrors -f 5' command could be used for getting updated mirrors list"
-        best_server_match=$(grep '^Server = ' /etc/pacman.d/mirrorlist | head -1 | cut -c10- | sed "s|/*.stable/\$repo/\$arch||")
+        best_server_match=$(grep '^Server = ' /etc/pacman.d/mirrorlist | head -1 | cut -c10- | sed "s|/\(un\)*stable/.*||")
         sed -i "s|# build_mirror=.*|build_mirror=${best_server_match}|" $target_conf_file || { printf "$err_prepare_text"; }
         echo "Changed build mirror in manjaro tools configuration file to ${best_server_match}"
         git clone https://github.com/notuxius/manjaro-tools-profile.git
         echo "Build profile is located in user's home directory"
         echo "Profile ISOs can be built with 'buildiso -p plasmawaylandtest' command"
         
-        # select latest non-realtime kernel available
-        if [[ -x $(which mhwd-kernel) ]]; then
-            latest_nonrt_kernel="$(mhwd-kernel -l | cut -c11- | grep '^[0-9]' | grep '[^rt]$' | sort -nr | head -n1)"
-            sed -i "s|# kernel=.*|kernel=linux${latest_nonrt_kernel}|" $target_conf_file || { printf "$err_prepare_text"; }
-            echo "Changed kernel in manjaro tools configuration file to linux${latest_nonrt_kernel} - latest non-realtime available"
-        else
-            echo "Manjaro Kernel utility wasn't found"
-        fi
+        # select latest non-realtime kernel availabe in unstable repo
+        latest_nonrt_kernel=$(wget -q -O - $best_server_match/unstable/core/x86_64/core.db.tar.gz | tar -tvz | awk '{print $6}' | grep -- '^linux[0-9]' | grep -v 'headers' | grep -v 'desc' | sed "s|-.*||" | cut -c6- | sort -nr | head -n1)
+        sed -i "s|# kernel=.*|kernel=linux${latest_nonrt_kernel}|" $target_conf_file || { printf "$err_prepare_text"; }
+        echo "Changed kernel in manjaro tools configuration file to linux${latest_nonrt_kernel} - latest non-realtime available"
+        
+        echo "If ISO doesn't build with latest linux${latest_nonrt_kernel} kernel - try other versions available"
+            if [[ -x $(which mhwd-kernel 2> /dev/null) ]]; then
+                mhwd-kernel -l | cut -c11- | grep '^[0-9]' | grep '[^rt]$' | grep -vw "${latest_nonrt_kernel}" | sort -nr
+            fi
+        echo "or comment out 'kernel=...' string in manjaro tools configuration file"
         ;;
+        
   *) echo "Unable to select best build mirror and latest kernel - they could be changed manually in manjaro tools configuration file"
      echo "Unable to download profile - it could be obtained on https://github.com/notuxius/manjaro-tools-profile page"
      ;;
@@ -99,14 +102,22 @@ if [[ ${#1} -gt 0 ]]; then
         else
             while getopts "${opts}" arg; do
                 case "${arg}" in
-                    # comment additional desktop packages
-                    # change distribution release to ...codename-minimal-month.day.hour... version format
-                    m|c) sed -i 's|^\([^# ].*\)# minimal-packages-toggle$|# \1# minimal-packages-toggle|g' $desktop_packages_file || { printf "$err_prepare_text"; }; sed -i "s|.*dist_release=.*|dist_release=\$(source ${lsb_release_file}; echo \${DISTRIB_CODENAME,,})-minimal-\$(date --utc +%Y.%-m.%-d.%-H)|" $target_conf_file || { printf "$err_prepare_text"; }; echo "Minimal build - some additional desktop packages will not be included" ;;
+                    m|c) # comment additional desktop packages
+                         # change distribution release to ...codename-minimal-month.day.hour... version format
+                         sed -i 's|^\([^# ].*\)# minimal-packages-toggle$|# \1# minimal-packages-toggle|g' $desktop_packages_file || { printf "$err_prepare_text"; }
+                         sed -i "s|.*dist_release=.*|dist_release=\$(source ${lsb_release_file}; echo \${DISTRIB_CODENAME,,})-minimal-\$(date --utc +%Y.%-m.%-d.%-H)|" $target_conf_file || { printf "$err_prepare_text"; }
+                         echo "Minimal build - some additional desktop packages will not be included"
+                         ;;
                     
-                    # uncomment additional desktop packages
-                    # change distribution release to ...codename-month.day.hour... version format
-                    f|u) sed -i 's|^# \(.*\)# minimal-packages-toggle$|\1# minimal-packages-toggle|g' $desktop_packages_file || { printf "$err_prepare_text"; }; sed -i "s|.*dist_release=.*|dist_release=\$(source ${lsb_release_file}; echo \${DISTRIB_CODENAME,,})-\$(date --utc +%Y.%-m.%-d.%-H)|" $target_conf_file || { printf "$err_prepare_text"; }; echo "Full build - some additional desktop packages will be included" ;;
-                    *) echo $err_arg_text; exit 1 ;;
+                    f|u) # uncomment additional desktop packages
+                         # change distribution release to ...codename-month.day.hour... version format
+                         sed -i 's|^# \(.*\)# minimal-packages-toggle$|\1# minimal-packages-toggle|g' $desktop_packages_file || { printf "$err_prepare_text"; }
+                         sed -i "s|.*dist_release=.*|dist_release=\$(source ${lsb_release_file}; echo \${DISTRIB_CODENAME,,})-\$(date --utc +%Y.%-m.%-d.%-H)|" $target_conf_file || { printf "$err_prepare_text"; }
+                         echo "Full build - some additional desktop packages will be included"
+                         ;;
+                    
+                    *) echo $err_arg_text; exit 1
+                       ;;
                 esac
             done
         fi
@@ -115,7 +126,7 @@ if [[ ${#1} -gt 0 ]]; then
         # cat $desktop_packages_file
         
     else
-        echo "Desktop packages files cannot be written - no changes been made"
+        echo "Desktop packages files cannot be written - no changes has been made"
     fi
 fi
 
